name: "@nidoz/development"

services:
    turso:
        image: ghcr.io/tursodatabase/libsql-server:v0.24.33
        environment:
            - SQLD_NODE=primary
            - SQLD_HTTP_AUTH=${TURSO_AUTH_TOKEN:-basic:ZGV2OnBhc3N3b3Jk}
        ports:
            - "${TURSO_HTTP_PORT:-36100}:8080"
            - "${TURSO_GRPC_PORT:-36101}:5001"
        restart: always
        volumes:
            - ../../.dockerVolume/libsql:/var/lib/sqld
